services:
  porto:
    build: .
    ports:
      - "1370:80"
    container_name: porto
    restart: unless-stopped

  porto-auth:
    build: ./server
    ports:
      - "3002:3001"
    container_name: porto-auth
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=qwerty...
      - DB_NAME=porto
      - JWT_SECRET=***      - PORT=3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - porto
    restart: unless-stopped
